name: Session2 Class Work

on:
  push:
    branches:
      - feature/session2-class
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      reason:
        description: 'Reason for deploy'
        required: false
        type: string


jobs:
  event-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Report Event
        run: |
        echo "Triggered by: ${{ github.event_name }}"

      - name: Report Event
        run: |
        echo "Branch: ${{ github.ref_name }}





